/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwareproject.view;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import softwareproject.controller.FormController;
import softwareproject.controller.ListPopulator;
import softwareproject.controller.NoteController;
import softwareproject.model.Activity;
import softwareproject.model.Assessment;
import softwareproject.model.Milestone;
import softwareproject.model.Note;
import softwareproject.model.StudyTask;

/**
 *
 * @author Daniel
 */
public class ActivityWindow extends javax.swing.JFrame {
    Activity act;
    Assessment a;
    ModuleOverview mo;
    
    /**
     * Creates new form MilestoneWindow
     */
    public ActivityWindow(Activity act, Assessment a, ModuleOverview mo) {
        this.act = act;
        this.a = a;
        this.mo = mo;
        initComponents();
        fillComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTaskWindow = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTitlePre = new javax.swing.JLabel();
        lblAssessmentPre = new javax.swing.JLabel();
        lblAssessment = new javax.swing.JLabel();
        lblStatusPre = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDescPre = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblTasks = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstTasks = new javax.swing.JList();
        btnClose = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstNotes = new javax.swing.JList();
        lblTasks1 = new javax.swing.JLabel();
        btnAddNote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTaskWindow.setText("Activity Window");

        lblTitle.setText("ActivityTitle");

        lblTitlePre.setText("Title:");

        lblAssessmentPre.setText("Assessment:");

        lblAssessment.setText("ActivityTitle");

        lblStatusPre.setText("Status:");

        lblStatus.setText("STATUS");

        lblDescPre.setText("Description:");

        txtDescription.setEditable(false);
        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane4.setViewportView(txtDescription);

        lblTasks.setText("Associated Tasks");

        lstTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTasksMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstTasks);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lstNotes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstNotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstNotesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(lstNotes);

        lblTasks1.setText("Notes");

        btnAddNote.setText("Add Note");
        btnAddNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblTaskWindow)
                        .addGap(0, 239, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDescPre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAssessmentPre)
                                            .addComponent(lblTitlePre))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTitle)
                                            .addComponent(lblAssessment)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(lblStatusPre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblStatus)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTasks)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTasks1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaskWindow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitlePre)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssessmentPre)
                    .addComponent(lblAssessment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusPre)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescPre)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTasks1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTasks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnAddNote))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
        dispose();
        mo.fillComponents();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void lstTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTasksMouseClicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            TaskWindow tw = new TaskWindow((StudyTask)list.getSelectedValue(), a, mo);
            tw.setVisible(true);
        }
    }//GEN-LAST:event_lstTasksMouseClicked

    private void lstNotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstNotesMouseClicked
        
    }//GEN-LAST:event_lstNotesMouseClicked

    private void btnAddNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNoteActionPerformed
        NoteForm nf = new NoteForm(act, this);
        nf.setVisible(true);
    }//GEN-LAST:event_btnAddNoteActionPerformed
    
    public void fillComponents(){
        lblTitle.setText(act.getName());
        lblAssessment.setText(a.getName());
        txtDescription.setText(act.getDescription());
        if(act.getIsFinished()){
            lblStatus.setText("Complete");
        }else{
            lblStatus.setText("In Progress");
        }
        
        ListPopulator<StudyTask> tasks = new ListPopulator();
        tasks.populateJList(act.getTasks(), lstTasks);
        
        DefaultListModel<String> lm = new DefaultListModel();
        for(Note n : act.getNotes()){
            lm.addElement(NoteController.getNoteAsString(n));        
        }
        lstNotes.setModel(lm);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNote;
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAssessment;
    private javax.swing.JLabel lblAssessmentPre;
    private javax.swing.JLabel lblDescPre;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusPre;
    private javax.swing.JLabel lblTaskWindow;
    private javax.swing.JLabel lblTasks;
    private javax.swing.JLabel lblTasks1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitlePre;
    private javax.swing.JList lstNotes;
    private javax.swing.JList lstTasks;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
