/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwareproject.view;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import softwareproject.model.Activity;
import softwareproject.model.Assessment;
import softwareproject.model.Milestone;
import softwareproject.model.StudyTask;

/**
 *
 * @author Daniel
 */
public class MilestoneWindow extends javax.swing.JFrame {
    ModuleOverview mo;
    Milestone m;
    Assessment a;
    
    /**
     * Creates new form MilestoneWindow
     */
    public MilestoneWindow(Milestone m, Assessment a, ModuleOverview mo) {
        this.m = m;
        this.mo = mo;
        this.a = a;
        initComponents();
        fillComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProgress = new javax.swing.JLabel();
        lblTaskWindow = new javax.swing.JLabel();
        pbMilestoneProgress = new javax.swing.JProgressBar();
        lblTitle = new javax.swing.JLabel();
        lblTitlePre = new javax.swing.JLabel();
        lblAssessmentPre = new javax.swing.JLabel();
        lblAssessment = new javax.swing.JLabel();
        lblDeadline = new javax.swing.JLabel();
        lblDeadlinePre = new javax.swing.JLabel();
        lblStatusPre = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDescPre = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblTasks = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstTasks = new javax.swing.JList();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProgress.setText("Progress");

        lblTaskWindow.setText("Milestone Window");

        pbMilestoneProgress.setForeground(new java.awt.Color(51, 204, 0));

        lblTitle.setText("MilestoneTitle");

        lblTitlePre.setText("Title:");

        lblAssessmentPre.setText("Assessment:");

        lblAssessment.setText("AssessmentTitle");

        lblDeadline.setText("Deadline");

        lblDeadlinePre.setText("Deadline:");

        lblStatusPre.setText("Status:");

        lblStatus.setText("STATUS");

        lblDescPre.setText("Description:");

        txtDescription.setEditable(false);
        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane4.setViewportView(txtDescription);

        lblTasks.setText("Associated Tasks");

        lstTasks.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTasksMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstTasks);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblTaskWindow)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pbMilestoneProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDescPre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProgress)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDeadlinePre)
                                            .addComponent(lblAssessmentPre)
                                            .addComponent(lblTitlePre))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTitle)
                                            .addComponent(lblAssessment)
                                            .addComponent(lblDeadline)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(lblStatusPre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblStatus)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTasks)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaskWindow)
                .addGap(10, 10, 10)
                .addComponent(lblProgress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbMilestoneProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitlePre)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssessmentPre)
                    .addComponent(lblAssessment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeadlinePre)
                    .addComponent(lblDeadline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusPre)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescPre)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTasks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
        dispose();
        mo.fillComponents();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void lstTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTasksMouseClicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            TaskWindow tw = new TaskWindow((StudyTask)list.getSelectedValue(), a, mo);
            tw.setVisible(true);
        }
    }//GEN-LAST:event_lstTasksMouseClicked
    
    public void fillComponents(){
        lblTitle.setText(m.getTitle());
        lblAssessment.setText(a.getName());
        lblDeadline.setText(m.getDeadline().toString());
        txtDescription.setText(m.getDescription());
        
        double taskTotalCount = 0;
        double taskCompleteCount = 0;
        DefaultListModel<StudyTask> lmTask = new DefaultListModel();
        for(StudyTask t: m.getRelatedTasks()){
            taskTotalCount++;
            lmTask.addElement(t);
            if(t.getIsComplete())
                taskCompleteCount++;
        }
        lstTasks.setModel(lmTask);
        pbMilestoneProgress.setMinimum(0);
        pbMilestoneProgress.setMaximum(100);
        int progress = (int)(taskCompleteCount/taskTotalCount*100);
        pbMilestoneProgress.setValue(progress);
        if(progress == 100){
            m.setIsComplete(true);
            lblStatus.setText("Complete");
        }else{
            m.setIsComplete(false);
            lblStatus.setText("In Progress");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAssessment;
    private javax.swing.JLabel lblAssessmentPre;
    private javax.swing.JLabel lblDeadline;
    private javax.swing.JLabel lblDeadlinePre;
    private javax.swing.JLabel lblDescPre;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusPre;
    private javax.swing.JLabel lblTaskWindow;
    private javax.swing.JLabel lblTasks;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitlePre;
    private javax.swing.JList lstTasks;
    private javax.swing.JProgressBar pbMilestoneProgress;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
