/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package softwareproject.view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import softwareproject.controller.AssessmentController;
import softwareproject.model.Assessment;
import softwareproject.model.ModuleOrganiser;

/**
 *
 * @author ybm14yju
 */
public class moduleListCell extends javax.swing.JPanel {

    /**
     * Creates new form moduleListCell
     */
    public moduleListCell(String moduleName, String moduleCode, ModuleOrganiser modOrg, ArrayList<Assessment> assessments) {
        initComponents();
        fillComponents(moduleName, moduleCode, modOrg, assessments);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModuleInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAssessments = new javax.swing.JList();
        lblAssessment = new javax.swing.JLabel();
        lblModOrg = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblModuleInfo.setText("Module Name");

        lstAssessments.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstAssessments.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAssessments.setEnabled(false);
        jScrollPane1.setViewportView(lstAssessments);

        lblAssessment.setText("Assessments");

        lblModOrg.setText("ModOrg");

        lblSemester.setText("Semester");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModuleInfo)
                    .addComponent(lblModOrg)
                    .addComponent(lblSemester))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAssessment)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(150, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblModuleInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblModOrg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSemester)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAssessment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillComponents(String moduleName, String moduleCode, ModuleOrganiser modOrg, ArrayList<Assessment> assessments){
        lblModuleInfo.setText(moduleName + " - " + moduleCode);
        lblModOrg.setText(modOrg.getName());
        if(moduleCode.endsWith("A")){
            lblSemester.setText("Semester 1");
        } else if(moduleCode.endsWith("Y")){
            lblSemester.setText("All Year");
        } else {
           lblSemester.setText("Semester 2"); 
        }
        
        DefaultListModel<String> lm = new DefaultListModel();
        for(Assessment as : assessments){
            lm.addElement(AssessmentController.getAssessmentAsString(as));        
        }
        lstAssessments.setModel(lm);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssessment;
    private javax.swing.JLabel lblModOrg;
    private javax.swing.JLabel lblModuleInfo;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JList lstAssessments;
    // End of variables declaration//GEN-END:variables
}
