package softwareproject.view;

import java.util.ArrayList;
import softwareproject.model.Assessment;
import softwareproject.model.ModuleOrganiser;

/**
 *
 * @author ybm14yju
 */
public class moduleListCellNav extends javax.swing.JPanel {

    /**
     * Creates new form moduleListCell
     */
    public moduleListCellNav(String moduleName, String moduleCode, String modOrg, ArrayList<Assessment> assessments) {
        initComponents();
        fillComponents(moduleName, moduleCode, modOrg, assessments);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModuleInfo = new javax.swing.JLabel();
        lblModOrg = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblModuleInfo.setText("Module Name");

        lblModOrg.setText("ModOrg");

        lblSemester.setText("Semester");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModuleInfo)
                    .addComponent(lblModOrg)
                    .addComponent(lblSemester))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModuleInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblModOrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSemester)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillComponents(String moduleName, String moduleCode, String modOrg, ArrayList<Assessment> assessments){
        lblModuleInfo.setText(moduleName + " - " + moduleCode);
        lblModOrg.setText(modOrg);
        if(moduleCode.endsWith("A")){
            lblSemester.setText("Semester 1");
        } else if(moduleCode.endsWith("Y")){
            lblSemester.setText("All Year");
        } else {
           lblSemester.setText("Semester 2"); 
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblModOrg;
    private javax.swing.JLabel lblModuleInfo;
    private javax.swing.JLabel lblSemester;
    // End of variables declaration//GEN-END:variables
    
}
