package softwareproject.view;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import softwareproject.controller.ActivityController;
import softwareproject.controller.ModuleController;
import softwareproject.controller.TaskController;
import softwareproject.model.Activity;
import softwareproject.model.Assessment;
import softwareproject.model.CourseTest;
import softwareproject.model.Coursework;
import softwareproject.model.Exam;
import softwareproject.model.Module;
import softwareproject.model.Task;

/**
 *
 * @author qxz14sru
 */
public class ModuleOverview extends javax.swing.JPanel {
    
    Assessment selectedAssessment;
    Module m;
    /**
     * Creates new form ModuleOverview
     */
    public ModuleOverview(Module m) {
        this.selectedAssessment = null;
        this.m = m;
        initComponents();
        loadAssessments();
        lstCoursework.setSelectedIndex(0);
    }
    
    public void fillComponents(){
        
        
        DefaultListModel<String> lmt = new DefaultListModel();
        DefaultListModel<String> lms = new DefaultListModel();
        
            for(Task t : selectedAssessment.getTasks()){
                lmt.addElement(selectedAssessment.getName() + " - " + TaskController.getStringFromTask(t));
            }   
            for(Activity a1 : selectedAssessment.getActivities()){
                lms.addElement(selectedAssessment.getName() + " - " + ActivityController.getActivityAsString(a1));
            }
        
        lstCurrentTasks.setModel(lmt);
        lstCurrentActivities.setModel(lms);
    }
    
    public void loadAssessments(){
        lblModTitle.setText(m.getModuleName() + " - " + m.getModuleCode());
        DefaultListModel<Exam> lme = new DefaultListModel();
        DefaultListModel<Coursework> lmcw = new DefaultListModel();
        DefaultListModel<CourseTest> lmct = new DefaultListModel();
        
        for(Assessment a : m.getAssessments()){

            if(a instanceof Exam){
                lme.addElement((Exam)a);
            }
            else if(a instanceof Coursework){
                lmcw.addElement((Coursework) a);
            }
            else {
                lmct.addElement((CourseTest) a);
            }
        }
        lstExam.setModel(lme);
        lstCoursework.setModel(lmcw);
        lstCourseTest.setModel(lmct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddTask = new javax.swing.JButton();
        btnAddMilestone = new javax.swing.JButton();
        btnAddActivity = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCoursework = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCourseTest = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstExam = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstCurrentActivities = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstCurrentTasks = new javax.swing.JList();
        lblCourseTest = new javax.swing.JLabel();
        lblExam = new javax.swing.JLabel();
        lblCoursework = new javax.swing.JLabel();
        lblCurrentTasks = new javax.swing.JLabel();
        lblCurrentActivities = new javax.swing.JLabel();
        lblModTitle = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(585, 562));
        setMinimumSize(new java.awt.Dimension(585, 562));

        btnAddTask.setText("Add Task");
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });

        btnAddMilestone.setText("Add Milestone");
        btnAddMilestone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMilestoneActionPerformed(evt);
            }
        });

        btnAddActivity.setText("Add Activity");

        lstCoursework.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstCoursework.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCoursework.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCourseworkValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCoursework);

        lstCourseTest.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstCourseTest.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCourseTest.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCourseTestValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstCourseTest);

        lstExam.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstExam.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstExam.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstExamValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstExam);

        lstCurrentActivities.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lstCurrentActivities);

        lstCurrentTasks.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstCurrentTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCurrentTasksMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(lstCurrentTasks);

        lblCourseTest.setText("Course Test");

        lblExam.setText("Exams");

        lblCoursework.setText("Coursework");

        lblCurrentTasks.setText("Current Tasks");

        lblCurrentActivities.setText("Current Activities");

        lblModTitle.setText("MODULE TITLE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCurrentTasks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(lblCurrentActivities)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddTask)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddMilestone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddActivity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCoursework)
                    .addComponent(lblCourseTest)
                    .addComponent(lblExam)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblModTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblModTitle)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoursework)
                    .addComponent(lblCurrentTasks)
                    .addComponent(lblCurrentActivities))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAddTask)
                                    .addComponent(btnAddMilestone)
                                    .addComponent(btnAddActivity))
                                .addGap(144, 144, 144))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblExam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCourseTest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 130, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMilestoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMilestoneActionPerformed
        MilestoneForm mf = new MilestoneForm(m);
        mf.setVisible(true);
    }//GEN-LAST:event_btnAddMilestoneActionPerformed

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        TaskForm tf = new TaskForm(m, this);
        tf.setVisible(true);
    }//GEN-LAST:event_btnAddTaskActionPerformed

    private void lstCurrentTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCurrentTasksMouseClicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            TaskWindow tw = new TaskWindow((Task)list.getSelectedValue(), selectedAssessment);
            tw.setVisible(true);
        }
    }//GEN-LAST:event_lstCurrentTasksMouseClicked

    private void lstCourseworkValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCourseworkValueChanged
        this.selectedAssessment = (Assessment)lstCoursework.getSelectedValue();
        lstExam.clearSelection();
        lstCourseTest.clearSelection();
        fillComponents();
    }//GEN-LAST:event_lstCourseworkValueChanged

    private void lstExamValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstExamValueChanged
        this.selectedAssessment = (Assessment)lstExam.getSelectedValue();
        lstCoursework.clearSelection();
        lstCourseTest.clearSelection();
        fillComponents();
    }//GEN-LAST:event_lstExamValueChanged

    private void lstCourseTestValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCourseTestValueChanged
        this.selectedAssessment = (Assessment)lstCourseTest.getSelectedValue();
        lstExam.clearSelection();
        lstCoursework.clearSelection();
        fillComponents();
    }//GEN-LAST:event_lstCourseTestValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddActivity;
    private javax.swing.JButton btnAddMilestone;
    private javax.swing.JButton btnAddTask;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCourseTest;
    private javax.swing.JLabel lblCoursework;
    private javax.swing.JLabel lblCurrentActivities;
    private javax.swing.JLabel lblCurrentTasks;
    private javax.swing.JLabel lblExam;
    private javax.swing.JLabel lblModTitle;
    private javax.swing.JList lstCourseTest;
    private javax.swing.JList lstCoursework;
    private javax.swing.JList lstCurrentActivities;
    private javax.swing.JList lstCurrentTasks;
    private javax.swing.JList lstExam;
    // End of variables declaration//GEN-END:variables
}
