/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package softwareproject.view;

import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import softwareproject.controller.ModuleController;
import softwareproject.controller.PanelController;
import softwareproject.model.Module;
import softwareproject.model.SemesterProfile;

/**
 *
 * @author ybm14yju
 */
public class OverviewDash extends javax.swing.JPanel implements ListCellRenderer<Module>{

    /**
     * Creates new form OverviewDash
     */
    SemesterProfile sp;
    PanelController pa;
    
    /**
     * Creates new form OverviewDashboard
     */
    public OverviewDash(PanelController pa) {
        sp = null;
        this.pa = pa;
        initComponents();
        fillComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewSemProf = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnOpenSem = new javax.swing.JButton();
        btnUpdateDeadlines = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstModules = new javax.swing.JList();

        btnNewSemProf.setText("New Semester Profile");
        btnNewSemProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSemProfActionPerformed(evt);
            }
        });

        lblWelcome.setText("Welcome - Overview Dashboard");

        btnOpenSem.setText("Open Semester Profile");

        btnUpdateDeadlines.setText("Update Deadlines");

        lstModules.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstModules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstModulesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstModules);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWelcome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNewSemProf)
                                .addGap(38, 38, 38)
                                .addComponent(btnOpenSem)
                                .addGap(42, 42, 42)
                                .addComponent(btnUpdateDeadlines)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewSemProf)
                    .addComponent(btnOpenSem)
                    .addComponent(btnUpdateDeadlines))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewSemProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSemProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewSemProfActionPerformed

    private void lstModulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstModulesMouseClicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            pa.setModulePanel(new ModuleOverview((Module)lstModules.getSelectedValue()));
                    
        }
    }//GEN-LAST:event_lstModulesMouseClicked

    private void fillComponents(){
        DefaultListModel<Module> lm = new DefaultListModel();
        
        if(sp != null){
            for(Module m :sp.getModules()){
                lm.addElement(m);  
                
            }
        }
        lstModules.setCellRenderer(this);
        lstModules.setModel(lm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewSemProf;
    private javax.swing.JButton btnOpenSem;
    private javax.swing.JButton btnUpdateDeadlines;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JList lstModules;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public Component getListCellRendererComponent(JList<? extends Module> jlist, Module e, int i, boolean bln, boolean bln1) {
        moduleListCell cellPane = new moduleListCell(e.getModuleName(), e.getModuleCode(), e.getModuleOrganiser(), ModuleController.getAssessments(e));
        if(bln){
            cellPane.setBackground(Color.gray);
        }
        
        return cellPane;
    }
    
    public void setsemP(SemesterProfile p){
        sp = p;
        fillComponents();
    }


}
