package softwareproject.view;

import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import softwareproject.controller.ActivityController;
import softwareproject.controller.NoteController;
import softwareproject.controller.TaskController;
import softwareproject.model.Activity;
import softwareproject.model.Assessment;
import softwareproject.model.Note;
import softwareproject.model.Task;

/**
 *
 * @author qxz14sru
 */
public class TaskWindow extends javax.swing.JFrame {
    private Task t;
    private Assessment a;

    /**
     * Creates new form TaskWindow
     */
    public TaskWindow(Task t, Assessment a) {
        this.t = t;
        this.a = a;
        initComponents();
        fillComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddNote = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        pbTaskProgress = new javax.swing.JProgressBar();
        lblProgress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAttachedActivities = new javax.swing.JList();
        lblAttachActivities = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstNotes = new javax.swing.JList();
        lblNotes = new javax.swing.JLabel();
        lblTaskWindow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAddNote.setText("Add Note");
        btnAddNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNoteActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblProgress.setText("Progress");

        lstAttachedActivities.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstAttachedActivities.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstAttachedActivities);

        lblAttachActivities.setText("Attatched Activities");

        lstNotes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstNotes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstNotes);

        lblNotes.setText("Notes");

        lblTaskWindow.setText("Task Window");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(pbTaskProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProgress)
                            .addComponent(lblAttachActivities)
                            .addComponent(lblNotes))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTaskWindow)
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTaskWindow)
                .addGap(10, 10, 10)
                .addComponent(lblProgress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbTaskProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAttachActivities)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnAddNote))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNoteActionPerformed
        //Open noteform.
        NoteForm nf = new NoteForm(t);
        nf.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnAddNoteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    
    private void fillComponents(){
        DefaultListModel<String> lm = new DefaultListModel();
        for(Note n : t.getNotes()){
            lm.addElement(NoteController.getNoteAsString(n));        
        }
        lstNotes.setModel(lm);
        
        double actTotalCount = 0;
        double actCompleteCount = 0;
        DefaultListModel<String> lm1 = new DefaultListModel();
        for(Activity act : TaskController.getsActivitesByTask(t, a)){
            lm1.addElement(ActivityController.getActivityAsString(act));
            actTotalCount++;
            if(act.getIsFinished())
                actCompleteCount++;
        }
        lstAttachedActivities.setModel(lm1);
        
        pbTaskProgress.setMinimum(0);
        pbTaskProgress.setMaximum(100);
        pbTaskProgress.setValue((int)(actCompleteCount/actTotalCount*100));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNote;
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAttachActivities;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblTaskWindow;
    private javax.swing.JList lstAttachedActivities;
    private javax.swing.JList lstNotes;
    private javax.swing.JProgressBar pbTaskProgress;
    // End of variables declaration//GEN-END:variables
}
