package softwareproject.view;

import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import softwareproject.controller.ActivityController;
import softwareproject.controller.NoteController;
import softwareproject.controller.TaskController;
import softwareproject.model.Activity;
import softwareproject.model.Assessment;
import softwareproject.model.Note;
import softwareproject.model.Task;

/**
 *
 * @author qxz14sru
 */
public class TaskWindow extends javax.swing.JFrame {
    private Task t;
    private Assessment a;

    /**
     * Creates new form TaskWindow
     */
    public TaskWindow(Task t, Assessment a) {
        this.t = t;
        this.a = a;
        initComponents();
        fillComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddNote = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        pbTaskProgress = new javax.swing.JProgressBar();
        lblProgress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAttachedActivities = new javax.swing.JList();
        lblAttachActivities = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstNotes = new javax.swing.JList();
        lblNotes = new javax.swing.JLabel();
        lblTaskWindow = new javax.swing.JLabel();
        lblDependent = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstDependent = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblTask = new javax.swing.JLabel();
        lblAssessment = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnComplete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAddNote.setText("Add Note");
        btnAddNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNoteActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        pbTaskProgress.setForeground(new java.awt.Color(51, 204, 0));

        lblProgress.setText("Progress");

        lstAttachedActivities.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstAttachedActivities.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstAttachedActivities);

        lblAttachActivities.setText("Attatched Activities");

        lstNotes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstNotes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstNotes);

        lblNotes.setText("Notes");

        lblTaskWindow.setText("Task Window");

        lblDependent.setText("Dependencies");

        lstDependent.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstDependent.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(lstDependent);

        jLabel1.setText("Task:");

        jLabel2.setText("Description:");

        jLabel3.setText("Time:");

        jLabel4.setText("Assessment:");

        txtDescription.setEditable(false);
        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane4.setViewportView(txtDescription);

        lblTask.setText("TaskTitle");

        lblAssessment.setText("AssessmentTitle");

        lblTime.setText("TimeAllocated");

        btnComplete.setText("Mark as Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTaskWindow)
                .addGap(309, 309, 309))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnComplete)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbTaskProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddNote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClose))
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTask)
                                            .addComponent(lblAssessment)
                                            .addComponent(lblTime))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProgress)
                                    .addComponent(lblDependent)
                                    .addComponent(lblNotes)
                                    .addComponent(lblAttachActivities))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTaskWindow)
                .addGap(10, 10, 10)
                .addComponent(lblProgress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbTaskProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTask))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblAssessment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAttachActivities)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComplete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDependent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnAddNote))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNoteActionPerformed
        //Open noteform.
        NoteForm nf = new NoteForm(t, this);
        nf.setVisible(true);
    }//GEN-LAST:event_btnAddNoteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        if(lstAttachedActivities.getSelectedValue() != null){
            Activity a = (Activity)lstAttachedActivities.getSelectedValue();
            a.setIsFinished(true);
            fillComponents();
        }
    }//GEN-LAST:event_btnCompleteActionPerformed
    
    public void fillComponents(){
        DefaultListModel<String> lm = new DefaultListModel();
        for(Note n : t.getNotes()){
            lm.addElement(NoteController.getNoteAsString(n));        
        }
        lstNotes.setModel(lm);
        
        double actTotalCount = 0;
        double actCompleteCount = 0;
        DefaultListModel<Activity> lm1 = new DefaultListModel();
        for(Activity act : t.getActivities()){
            lm1.addElement(act);
            actTotalCount++;
            if(act.getIsFinished())
                actCompleteCount++;
        }
        lstAttachedActivities.setModel(lm1);
        
        DefaultListModel<Task> lmTask = new DefaultListModel();
        for(Task t : t.getDependencies()){
            lmTask.addElement(t);
        }
        lstDependent.setModel(lmTask);
        pbTaskProgress.setMinimum(0);
        pbTaskProgress.setMaximum(100);
        pbTaskProgress.setValue((int)(actCompleteCount/actTotalCount*100));
        
        lblTask.setText(t.getTitle());
        lblTime.setText(Integer.toString(t.getHours())+" Hr(s)");
        txtDescription.setText(t.getDescription());
        lblAssessment.setText(a.getName());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNote;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnComplete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAssessment;
    private javax.swing.JLabel lblAttachActivities;
    private javax.swing.JLabel lblDependent;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblTask;
    private javax.swing.JLabel lblTaskWindow;
    private javax.swing.JLabel lblTime;
    private javax.swing.JList lstAttachedActivities;
    private javax.swing.JList lstDependent;
    private javax.swing.JList lstNotes;
    private javax.swing.JProgressBar pbTaskProgress;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
